### ISSUE TITLE
Cannot find type 'R' in the scope

### ISSUE THREAD

**Issue by artxcoder** [mac-cain13/R.swift#894]
I have updated the pod to latest version (7.3.2). Generated the R.generated.swift file after build and dragged and dropped the file into project folder.

When I start running the app, it shows **Cannot find type 'R' in scope**

![Uploading Screenshot 2024-05-02 at 11.32.29 AM.png…]()

**Comment by mrgsdev** [comment]
I just had this error.
What worked for me:

1. Remove R.generated.swift via Xcode "Move to trash" 
also remove it from the recycle bin permanently
you're gonna get these errors **Cannot find 'R' in scope**
2. Press Command+R
you'll have Build Failed, but you'll still have autocreated  **R.generated.swift** 
3. Drag and drop the file to the root of the folder where *.xcworkspace and *.xcodeproj are located. 
Example:
/Users/mrgsdev/Desktop/PROJECT_NAME/PROJECT_NAME.xcworkspace
**/Users/mrgsdev/Desktop/PROJECT_NAME/R.generated.swift**
5. tick the **Copy items if needed** checkbox
6. Command+B

P.S I didn't have autogeneration of new colours and so on working, this helped me.

**Comment by mac-cain13** [comment]
Could you please retry to integrate with 7.5.0 by following the Readme and see if the issue still persists?

**Comment by jaltreuter** [comment]
@artxcoder were you updating from a much older version of R.swift, and is your error happening on a typealias meant to shorten `R.string.localizable` down to something more palatable?  Like `typealias LocString = R.string.localizable`?

If so, then TL;DR: you need to replace that typealias with `let LocString = R.string.localizable`

When I updated from 5.0.3 to 7.7.0 I got this same error message, on a typealias like I described above.  The reason the compiler can't find type 'R' is because in the latest version of R.swift, `R` **isn't a type anymore**, it's an object instance of type `_R`.  Similarly `R.string.localizable` is now an object of type `_R.string.localizable`, so you can't assign `R.string.localizable` to a typealias either.

If you change your code so instead of creating a globally accessible typealias it creates a globally accessible object instance, the error should go away without having to change the rest of your codebase.
