### ISSUE TITLE
Two instances of R.swift (library and project)

### ISSUE THREAD

**Issue by apemobilu** [mac-cain13/R.swift#290]
Hi,

I am trying to use the awesome R.swift lib in my project.
My project is full Swift and consists in two targets:
- MyProject (main target)
- MyFMK (dynamic framework)

I have successfully installed R.swift in MyFMK and can use it without any problem (via the added build phase). If I set the access of R.swift to public, I can access the R struct of MyFMK in MyProject.
However, I would like MyProject to have also its own R struct because MyProject will also contain images/xib/storyboards/strings/etc.
So, how can I do it? Because if I add a build phase to the target of MyProject, when I type R... I only see the content from MyProject and not MyFMK. In addition to that, the R struct from MyProject has some errors. It tries to access controllers from MyFMK

Example (from struct _R -> struct storyboard -> struct main):
`let myVC = StoryboardViewControllerResource<MyFMK.MyVC>(identifier: "MyVC")`
That generates the error `MyVC is not a member of type MyFMK`.

MyVC is a UIViewController that is in MyFMK and is public.

Thanks for your help

**Comment by tomlokhorst** [comment]
The two R.swift build steps in each target should work independently.
Make sure the two build steps write to a separate directory so that they don't overwrite each other.

In my app I have:

 - MyProject target build step: `"$PODS_ROOT/R.swift/rswift" "$SRCROOT/MyProject/Resources"`
 - MyFMK target build step: `"$PODS_ROOT/R.swift/rswift" "$SRCROOT/MyFMK/Resources"`

**Comment by apemobilu** [comment]
Hi,

This is exactly what I have done, but it does not work. MyProject does not have access to the R from  MyFMK.
I have 2 R.generated.swift files generated. One in MyProject/Resources and one in MyFMK/Resources (this one has been generated with --accessLevel public). 
When I start typing R. in MyProject, I don't see stuff from R from MyFMK. And R from MyProject has errors (as I wrote in my first post).

**Comment by tomlokhorst** [comment]
The R struct from the library should be available in MyProject via `MyFMK.R.*`, with `import MyFMK` at the top of the file.

Regarding the errors in the R.generated.swift from MyProject:
Do you use the MyVC from MyFMK in your storyboard?
Is it public, or internal to the framework?

**Comment by apemobilu** [comment]
Hi,

I managed to solve the issue. There was an error in my naming convention so MyProject could not properly access MyFMK.R.

Thanks for your help and for your really nice lib 👍
